language: python
python:
  - "3.6"
install:
  - sudo apt install graphviz
  - pip install pylint funcparserlib colorama jinja2 pycodestyle hypothesis pygments graphviz
script:
  - nosetests
notifications:
  email: false
